### PR TITLE
Use Futhark v0.16.2.

### PR DESCRIPTION
**Pull request by porcuquine**
Use a released version of Futhark, [v0.16.2](https://github.com/diku-dk/futhark/releases/tag/v0.16.2) at commit [2cd88bd](https://github.com/diku-dk/futhark/commit/2cd88bd1b64c1e7d3aebcfa41c3473be845277b7).

TODO:
- [x] Check the generated code for performance regression downstream.

### CODE REVIEW

**Comment by porcuquine** [comment]
There is no observable change in performance. The difference in a test now is in the noise (although it reads as a tiny improvement — certainly not a regression). So this change is safe from a performance perspective.

Before:
```
➜  gbench git:(master) ✗ RUST_LOG=info cargo run --release
   Compiling neptune-triton v1.1.0
   Compiling neptune v1.1.2 (/home/porcuquine/dev/neptune)
   Compiling gbench v0.5.4 (/home/porcuquine/dev/neptune/gbench)
    Finished release [optimized] target(s) in 1m 00s
     Running `target/release/gbench`
[2020-07-17T17:26:30Z INFO  gbench] KiB: 4194304
[2020-07-17T17:26:30Z INFO  gbench] leaves: 134217728
[2020-07-17T17:26:30Z INFO  gbench] max column batch size: 400000
[2020-07-17T17:26:30Z INFO  gbench] max tree batch size: 700000
[2020-07-17T17:26:30Z WARN  neptune::cl] Cannot get device list for platform: Clover!
[2020-07-17T17:26:30Z INFO  gbench] GPU[Bus-id: 23] --> Run 0
[2020-07-17T17:26:30Z INFO  gbench] GPU[Bus-id: 23]: Creating ColumnTreeBuilder
[2020-07-17T17:26:31Z WARN  neptune::cl] Cannot get device list for platform: Clover!
[2020-07-17T17:26:37Z INFO  gbench] GPU[Bus-id: 23]: ColumnTreeBuilder created
[2020-07-17T17:26:37Z INFO  gbench] GPU[Bus-id: 23]: Using effective batch size 400000 to build columns
[2020-07-17T17:26:37Z INFO  gbench] GPU[Bus-id: 23]: adding column batches
[2020-07-17T17:26:37Z INFO  gbench] GPU[Bus-id: 23]: start commitment
...............................................................................................................................................................................................................................................................................................................................................
[2020-07-17T17:28:46Z INFO  gbench] GPU[Bus-id: 23]: adding final column batch and building tree
[2020-07-17T17:29:05Z INFO  gbench] GPU[Bus-id: 23]: end commitment
[2020-07-17T17:29:05Z INFO  gbench] GPU[Bus-id: 23]: commitment time: 148.466870031s
```

Using this branch:
```
➜  gbench git:(master) ✗ RUST_LOG=info cargo run --release
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/gbench`
[2020-07-17T17:52:54Z INFO  gbench] KiB: 4194304
[2020-07-17T17:52:54Z INFO  gbench] leaves: 134217728
[2020-07-17T17:52:54Z INFO  gbench] max column batch size: 400000
[2020-07-17T17:52:54Z INFO  gbench] max tree batch size: 700000
[2020-07-17T17:52:54Z WARN  neptune::cl] Cannot get device list for platform: Clover!
[2020-07-17T17:52:54Z INFO  gbench] GPU[Bus-id: 23] --> Run 0
[2020-07-17T17:52:54Z INFO  gbench] GPU[Bus-id: 23]: Creating ColumnTreeBuilder
[2020-07-17T17:52:56Z WARN  neptune::cl] Cannot get device list for platform: Clover!
[2020-07-17T17:53:01Z INFO  gbench] GPU[Bus-id: 23]: ColumnTreeBuilder created
[2020-07-17T17:53:01Z INFO  gbench] GPU[Bus-id: 23]: Using effective batch size 400000 to build columns
[2020-07-17T17:53:01Z INFO  gbench] GPU[Bus-id: 23]: adding column batches
[2020-07-17T17:53:01Z INFO  gbench] GPU[Bus-id: 23]: start commitment
...............................................................................................................................................................................................................................................................................................................................................
[2020-07-17T17:55:10Z INFO  gbench] GPU[Bus-id: 23]: adding final column batch and building tree
[2020-07-17T17:55:29Z INFO  gbench] GPU[Bus-id: 23]: end commitment
[2020-07-17T17:55:29Z INFO  gbench] GPU[Bus-id: 23]: commitment time: 148.255878116s
```

**Comment by porcuquine** [comment]
@athas Can you confirm that this change correctly moves `neptune-triton` to a 'good', released version of Futhark?

**Comment by athas** [comment]
Yes, 0.16.2 is a very good release!

**Comment by porcuquine** [comment]
Thank you.

**Review by cryptonemo — APPROVED** [review]

**Pull request merged**
